
// API 1
GET http://localhost:3000/players/

####

//API2
POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}